version: '3.5'

services:
  api:
    build: ./api/
    restart: always
    ports:
      - 3002:3000
    environment:
      WEBTV_API_PORT: ${WEBTV_API_PORT}
      TWITCH_CLIENT_ID: ${TWITCH_CLIENT_ID}
      TWITCH_CLIENT_ID_SECRET: ${TWITCH_CLIENT_ID_SECRET}
      REDIRECT_URI: ${REACT_APP_API_HOST}
      REDIRECT_URI_APP: ${APP_HOST}
    volumes:
      - ./api/:/usr/src/
      - ./api/package.json:/usr/src/package.json
      - /usr/src/node_modules
    labels:
      traefik.enable: "true"
      traefik.docker.network: "traefik_network"
      traefik.http.services.tvapibaptistemrtfr.loadbalancer.server.port: "3000"
      #HTTP
      traefik.http.routers.api-tvbaptistemrtfr.entrypoints: "http"
      traefik.http.routers.api-tvbaptistemrtfr.rule: "Host(`bapmarty.fr`) && Path(`/api`)"
      traefik.http.routers.api-tvbaptistemrtfr.middlewares: redirect-https
      #HTTPS
      traefik.http.routers.api-tvbaptistemrtfr-secure.entrypoints: "https"
      traefik.http.routers.api-tvbaptistemrtfr-secure.rule: "Host(`bapmarty.fr`) && Path(`/api`)"
      #TLS
      traefik.http.routers.api-tvbaptistemrtfr-secure.tls: "true"
      traefik.http.routers.api-tvbaptistemrtfr-secure.tls.certresolver: "le-bapmarty"
      traefik.http.routers.api-tvbaptistemrtfr-secure.tls.domains[0].main: "bapmarty.fr"
      #Redirect https
      traefik.http.middlewares.redirect-https.redirectscheme.scheme: "https"
      traefik.http.middlewares.redirect-https.redirectscheme.permanent: "true"
    networks:
      - webtv

  app:
    build: ./app/
    restart: always
    ports:
      - 3001:3000
    environment:
      REACT_APP_API_HOST: ${REACT_APP_API_HOST}
      REACT_APP_CLIENT_ID: ${TWITCH_CLIENT_ID}
    volumes:
      - ./app/package.json:/usr/src/package.json
      - ./app/:/usr/src/
      - /usr/src/node_modules
    labels:
      traefik.enable: "true"
      traefik.docker.network: "traefik_network"
      traefik.http.services.tvbaptistemrtfr.loadbalancer.server.port: "3000"
      #HTTP
      traefik.http.routers.front-tvbaptistemrtfr.entrypoints: "http"
      traefik.http.routers.front-tvbaptistemrtfr.rule: "Host(`bapmarty.fr`)"
      traefik.http.routers.front-tvbaptistemrtfr.middlewares: redirect-https
      #HTTPS
      traefik.http.routers.front-tvbaptistemrtfr-secure.entrypoints: "https"
      traefik.http.routers.front-tvbaptistemrtfr-secure.rule: "Host(`bapmarty.fr`)"
      #TLS
      traefik.http.routers.front-tvbaptistemrtfr-secure.tls: "true"
      traefik.http.routers.front-tvbaptistemrtfr-secure.tls.certresolver: "le-bapmarty"
      traefik.http.routers.front-tvbaptistemrtfr-secure.tls.domains[0].main: "bapmarty.fr"
      #Redirect https
      traefik.http.middlewares.redirect-https.redirectscheme.scheme: "https"
      traefik.http.middlewares.redirect-https.redirectscheme.permanent: "true"
    networks:
      - webtv

networks:
  webtv:
    name: webtv
