version: '3.5'

services:
  api:
    build: ./api/
    environment:
      WEBTV_API_PORT: ${WEBTV_API_PORT}
      TWITCH_CLIENT_ID: ${TWITCH_CLIENT_ID}
      TWITCH_CLIENT_ID_SECRET: ${TWITCH_CLIENT_ID_SECRET}
      CHANNEL_ID: ${CHANNEL_ID}
      REDIRECT_URI: ${REACT_APP_API_HOST}
      REDIRECT_URI_APP: ${APP_HOST}
    volumes:
      - ./api/:/usr/src/
      - ./api/package.json:/usr/src/package.json
      - /usr/src/node_modules
    networks:
      - webtv_ci

  app:
    build: ./app/
    environment:
      REACT_APP_API_HOST: ${REACT_APP_API_HOST}
      REACT_APP_CLIENT_ID: ${TWITCH_CLIENT_ID}
    volumes:
      - ./app/package.json:/usr/src/package.json
      - ./app/:/usr/src/
      - /usr/src/node_modules
    networks:
      - webtv_ci

networks:
  webtv_ci:
    name: webtv_ci
