version: '3.5'

services:
  db:
    image: mongo
    restart: always
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - db_data:/data/db
    networks:
      - webtv

  api:
    build: ./api/
    restart: always
    environment:
      WEBTV_API_PORT: ${WEBTV_API_PORT}
      TWITCH_CLIENT_ID: ${TWITCH_CLIENT_ID}
      TWITCH_CLIENT_ID_SECRET: ${TWITCH_CLIENT_ID_SECRET}
      REDIRECT_URI: ${REACT_APP_API_HOST}
    volumes:
      - ./api/:/usr/src/
      - ./api/package.json:/usr/src/package.json
      - /usr/src/node_modules
    labels:
      traefik.enable: "true"
      traefik.docker.network: "traefik_network"
      traefik.http.services.tvapibaptistemrtfr.loadbalancer.server.port: "3000"
      #HTTP
      traefik.http.routers.api-tvbaptistemrtfr.entrypoints: "http"
      traefik.http.routers.api-tvbaptistemrtfr.rule: "Host(`tvapi.baptistemrt.fr`) || Host(`api.bapmarty.fr`)"
      traefik.http.routers.api-tvbaptistemrtfr.middlewares: redirect-https
      #HTTPS
      traefik.http.routers.api-tvbaptistemrtfr-secure.entrypoints: "https"
      traefik.http.routers.api-tvbaptistemrtfr-secure.rule: "Host(`tvapi.baptistemrt.fr`) || Host(`api.bapmarty.fr`)"
      #TLS
      traefik.http.routers.api-tvbaptistemrtfr-secure.tls: "true"
      traefik.http.routers.api-tvbaptistemrtfr-secure.tls.certresolver: "le"
      traefik.http.routers.api-tvbaptistemrtfr-secure.tls.domains[0].main: "tvapi.baptistemrt.fr"
      traefik.http.routers.api-tvbaptistemrtfr-secure.tls.domains[0].sans: "api.bapmarty.fr"
      #Redirect https
      traefik.http.middlewares.redirect-https.redirectscheme.scheme: "https"
      traefik.http.middlewares.redirect-https.redirectscheme.permanent: "true"
    networks:
      - traefik_network
      - webtv

  app:
    build: ./app/
    restart: always
    environment:
      REACT_APP_API_HOST: ${REACT_APP_API_HOST}
      REACT_APP_CLIENT_ID: ${TWITCH_CLIENT_ID}
    volumes:
      - ./app/package.json:/usr/src/package.json
      - ./app/:/usr/src/
      - /usr/src/node_modules
    labels:
      traefik.enable: "true"
      traefik.docker.network: "traefik_network"
      traefik.http.services.tvbaptistemrtfr.loadbalancer.server.port: "3000"
      #HTTP
      traefik.http.routers.front-tvbaptistemrtfr.entrypoints: "http"
      traefik.http.routers.front-tvbaptistemrtfr.rule: "Host(`tv.baptistemrt.fr`) || Host(`tv.bapmarty.fr`)"
      traefik.http.routers.front-tvbaptistemrtfr.middlewares: redirect-https
      #HTTPS
      traefik.http.routers.front-tvbaptistemrtfr-secure.entrypoints: "https"
      traefik.http.routers.front-tvbaptistemrtfr-secure.rule: "Host(`tv.baptistemrt.fr`) || Host(`tv.bapmarty.fr`)"
      #TLS
      traefik.http.routers.front-tvbaptistemrtfr-secure.tls: "true"
      traefik.http.routers.front-tvbaptistemrtfr-secure.tls.certresolver: "le"
      traefik.http.routers.front-tvbaptistemrtfr-secure.tls.domains[0].main: "tv.baptistemrt.fr"
      traefik.http.routers.front-tvbaptistemrtfr-secure.tls.domains[0].sans: "tv.bapmarty.fr"
      #Redirect https
      traefik.http.middlewares.redirect-https.redirectscheme.scheme: "https"
      traefik.http.middlewares.redirect-https.redirectscheme.permanent: "true"
    networks:
      - traefik_network
      - webtv

networks:
  traefik_network:
    external: true
  webtv:
    name: webtv

volumes:
  db_data: {}
