version: '3.5'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - ~/db/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ~/db/mongo/data:/data/db
    networks:
      - webtv_ci

  api:
    build: ./api/
    restart: always
    environment:
      WEBTV_API_PORT: ${WEBTV_API_PORT}
      TWITCH_CLIENT_ID: ${TWITCH_CLIENT_ID}
      TWITCH_CLIENT_ID_SECRET: ${TWITCH_CLIENT_ID_SECRET}
      CHANNEL_ID: ${CHANNEL_ID}
      REDIRECT_URI: ${REACT_APP_API_HOST}
      REDIRECT_URI_APP: ${APP_HOST}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      SECRET_TOKEN_JWT: ${SECRET_TOKEN_JWT}
    volumes:
      - ./api/:/usr/src/
      - ./api/package.json:/usr/src/package.json
      - /usr/src/node_modules
    networks:
      - webtv_ci

  app:
    build: ./app/
    restart: always
    environment:
      REACT_APP_API_HOST: ${REACT_APP_API_HOST}
      REACT_APP_CLIENT_ID: ${TWITCH_CLIENT_ID}
    volumes:
      - ./app/package.json:/usr/src/package.json
      - ./app/:/usr/src/
      - /usr/src/node_modules
    networks:
      - webtv_ci

networks:
  webtv_ci:
    name: webtv_ci
